import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { createClient } from '@supabase/supabase-js';
import { devUsers } from './dev-database.mjs';
import { demoPassword } from './demo-api.mjs';

function cli(args, capture = false) {
  const result = spawnSync(process.execPath, ['node_modules/supabase/dist/supabase.js', ...args], {
    stdio: capture ? ['ignore', 'pipe', 'pipe'] : 'inherit', encoding: 'utf8',
  });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error('Local Supabase command failed. Install and start Docker Desktop, then retry.');
  return result.stdout;
}

if (process.argv.includes('--stop')) {
  cli(['stop']);
} else {
  let previous = '';
  try { previous = await readFile('.env.local', 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (previous && !previous.startsWith('# Generated by npm run dev:local\n')) {
    throw new Error('.env.local already exists. Move it aside before creating the local development configuration.');
  }
  cli(['start']);
  cli(['migration', 'up', '--local']);
  const status = JSON.parse(cli(['status', '-o', 'json'], true));
  const url = status.API_URL;
  if (!url || !['127.0.0.1', 'localhost'].includes(new URL(url).hostname)) throw new Error('Expected a local Supabase API URL.');
  const admin = createClient(url, status.SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
  const { data, error } = await admin.auth.admin.listUsers();
  if (error) throw error;
  for (const fixture of devUsers) {
    if (data.users.some(user => user.email === fixture.email)) continue;
    const result = await admin.auth.admin.createUser({ email: fixture.email, password: demoPassword, email_confirm: true });
    if (result.error) throw result.error;
  }
  await writeFile('.env.local', `# Generated by npm run dev:local\nVITE_SUPABASE_URL=${url}\nVITE_SUPABASE_PUBLISHABLE_KEY=${status.ANON_KEY}\n`);
  console.log(`Local Supabase is ready. Run npm run dev.\nAccounts: alice@planner.test / bob@planner.test\nTest password: ${demoPassword}`);
}
